/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as RecipeSlugRouteImport } from './routes/recipe/$slug'
import { Route as DashboardCreateRouteImport } from './routes/dashboard/create'
import { Route as ChefUsernameRouteImport } from './routes/chef/$username'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/dashboard/create',
  path: '/dashboard/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefUsernameRoute = ChefUsernameRouteImport.update({
  id: '/chef/$username',
  path: '/chef/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chef/$username'
    | '/dashboard/create'
    | '/recipe/$slug'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chef/$username'
    | '/dashboard/create'
    | '/recipe/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/chef/$username'
    | '/dashboard/create'
    | '/recipe/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ChefUsernameRoute: typeof ChefUsernameRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  RecipeSlugRoute: typeof RecipeSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$username': {
      id: '/chef/$username'
      path: '/chef/$username'
      fullPath: '/chef/$username'
      preLoaderRoute: typeof ChefUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ChefUsernameRoute: ChefUsernameRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  RecipeSlugRoute: RecipeSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
