/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'
import { Route as ChefUsernameRouteImport } from './routes/chef.$username'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as RecipeSlugPrintRouteImport } from './routes/recipe.$slug.print'
import { Route as AuthedDashboardCreateRouteImport } from './routes/_authed/dashboard/create'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefUsernameRoute = ChefUsernameRouteImport.update({
  id: '/chef/$username',
  path: '/chef/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const RecipeSlugPrintRoute = RecipeSlugPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => RecipeSlugRoute,
} as any)
const AuthedDashboardCreateRoute = AuthedDashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/_authed/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/dashboard/create'
    | '/recipe/$slug/print'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/dashboard/create'
    | '/recipe/$slug/print'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authed/dashboard'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/_authed/dashboard/create'
    | '/recipe/$slug/print'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  ChefUsernameRoute: typeof ChefUsernameRoute
  RecipeSlugRoute: typeof RecipeSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$username': {
      id: '/chef/$username'
      path: '/chef/$username'
      fullPath: '/chef/$username'
      preLoaderRoute: typeof ChefUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/recipe/$slug/print': {
      id: '/recipe/$slug/print'
      path: '/print'
      fullPath: '/recipe/$slug/print'
      preLoaderRoute: typeof RecipeSlugPrintRouteImport
      parentRoute: typeof RecipeSlugRoute
    }
    '/_authed/dashboard/create': {
      id: '/_authed/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof AuthedDashboardCreateRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardCreateRoute: typeof AuthedDashboardCreateRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardCreateRoute: AuthedDashboardCreateRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface RecipeSlugRouteChildren {
  RecipeSlugPrintRoute: typeof RecipeSlugPrintRoute
}

const RecipeSlugRouteChildren: RecipeSlugRouteChildren = {
  RecipeSlugPrintRoute: RecipeSlugPrintRoute,
}

const RecipeSlugRouteWithChildren = RecipeSlugRoute._addFileChildren(
  RecipeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  ChefUsernameRoute: ChefUsernameRoute,
  RecipeSlugRoute: RecipeSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
