/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'
import { Route as ChefUsernameRouteImport } from './routes/chef.$username'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as RecipeSlugPrintRouteImport } from './routes/recipe.$slug.print'
import { Route as AuthedDashboardCreateRouteImport } from './routes/_authed/dashboard/create'
import { Route as AuthedDashboardEditIdRouteImport } from './routes/_authed/dashboard/edit.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefUsernameRoute = ChefUsernameRouteImport.update({
  id: '/chef/$username',
  path: '/chef/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const RecipeSlugPrintRoute = RecipeSlugPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => RecipeSlugRoute,
} as any)
const AuthedDashboardCreateRoute = AuthedDashboardCreateRouteImport.update({
  id: '/dashboard/create',
  path: '/dashboard/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardEditIdRoute = AuthedDashboardEditIdRouteImport.update({
  id: '/dashboard/edit/$id',
  path: '/dashboard/edit/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/edit/$id': typeof AuthedDashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/edit/$id': typeof AuthedDashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/chef/$username': typeof ChefUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRouteWithChildren
  '/_authed/dashboard/create': typeof AuthedDashboardCreateRoute
  '/recipe/$slug/print': typeof RecipeSlugPrintRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/edit/$id': typeof AuthedDashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/settings'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/dashboard/create'
    | '/recipe/$slug/print'
    | '/dashboard'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/settings'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/dashboard/create'
    | '/recipe/$slug/print'
    | '/dashboard'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authed/settings'
    | '/chef/$username'
    | '/recipe/$slug'
    | '/_authed/dashboard/create'
    | '/recipe/$slug/print'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  ChefUsernameRoute: typeof ChefUsernameRoute
  RecipeSlugRoute: typeof RecipeSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$username': {
      id: '/chef/$username'
      path: '/chef/$username'
      fullPath: '/chef/$username'
      preLoaderRoute: typeof ChefUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/recipe/$slug/print': {
      id: '/recipe/$slug/print'
      path: '/print'
      fullPath: '/recipe/$slug/print'
      preLoaderRoute: typeof RecipeSlugPrintRouteImport
      parentRoute: typeof RecipeSlugRoute
    }
    '/_authed/dashboard/create': {
      id: '/_authed/dashboard/create'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof AuthedDashboardCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/edit/$id': {
      id: '/_authed/dashboard/edit/$id'
      path: '/dashboard/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof AuthedDashboardEditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedDashboardCreateRoute: typeof AuthedDashboardCreateRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardEditIdRoute: typeof AuthedDashboardEditIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedDashboardCreateRoute: AuthedDashboardCreateRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardEditIdRoute: AuthedDashboardEditIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface RecipeSlugRouteChildren {
  RecipeSlugPrintRoute: typeof RecipeSlugPrintRoute
}

const RecipeSlugRouteChildren: RecipeSlugRouteChildren = {
  RecipeSlugPrintRoute: RecipeSlugPrintRoute,
}

const RecipeSlugRouteWithChildren = RecipeSlugRoute._addFileChildren(
  RecipeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  ChefUsernameRoute: ChefUsernameRoute,
  RecipeSlugRoute: RecipeSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
